RosBets/Controllers/ResultsController.cs
using PagedList;
using RosBets.Context;
using RosBets.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RosBets.Controllers
{
    public class ResultsController : Controller
    {
        RosBetsContext db = new RosBetsContext();
        // GET: Results

        

        public ActionResult ShowResults(int? page, DateTime? date1, DateTime? date2, string sport = "Все")
        {

            if (date1 == null)
            {
                date1 = default(DateTime);
            }

            if (date2 == null)
            {
                date2 = DateTime.Now;
            }

            ViewBag.date1 = date1;
            ViewBag.date2 = date2;
            ViewBag.sport = sport;

            int pageSize = 20;
            int pageNumber = (page ?? 1);

            List<Match> results = db.Matches
                   .Where(x => x.Finished == true)
                   .Include(x => x.Championship)
                   .Include(z => z.Championship.Sport)
                   .OrderBy(y => y.Championship.Name)
                   .ThenBy(x => x.Date)
                   .ToList();

            if (sport == "Все")
            {
                results = results
                   .Where(y => y.Date.Value.Date >= date1.Value.Date)
                   .Where(y => y.Date.Value.Date <= date2.Value.Date)
                   .ToList();

                return View(results.ToPagedList(pageNumber, pageSize));

            }

            results = results
                   .Where(x => x.Championship.Sport.Name == sport)
                   .Where(y => y.Date.Value.Date >= date1.Value.Date)
                   .Where(y => y.Date.Value.Date <= date2.Value.Date)
                   .ToList();

            return View(results.ToPagedList(pageNumber, pageSize));
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

RosBets/Views/Results/ShowResults.cshtml
@model PagedList.IPagedList<RosBets.Models.Match>
@using PagedList.Mvc;
@{ViewBag.Title = "Результаты"; }
<div class="container" style="margin-top: 20px; align-content: center;">
    <div class="row">
        @using (Html.BeginForm("ShowResults", "Results", FormMethod.Post))
        {
            <div class="row">
                <div class="col-sm-2" id="wrapper-dropdown" style="padding-top:15px;">
                    <label for="sport">Вид спорта:</label>
                    <select name="sport" id="sport">
                        <option value="Все" selected>Все</option>
                        <option value="Футбол">Футбол</option>
                        <option value="Хоккей">Хоккей</option>
                    </select>
                </div>
                <div class="col-md-3" style="padding-top:15px;">
                    <div class="col-md-2">C: </div>
                    <div class="col-md-10"><input type="date" id="date1" name="date1"></div>
                </div>
                <div class="col-md-3" style="padding-top:15px;">
                    <div class="col-md-2">По: </div>
                    <div class="col-md-10"><input type="date" id="date2" name="date2"></div>
                </div>
                <div class="col-md-4" style="padding-left: 100px; padding-top: 0px; padding-bottom: 10px;">
                    <button class="btn-filter" name="show" id="botShow">Отправить</button>
                </div>
            </div>
        }
    </div>


    <div class="result-story" id="result-story">


        @foreach (var match in Model.GroupBy(m => m.Championship.Name))
        {
            <div class="container result-box">
                <div class="col-sm-12 col-md-12 result-box__info row">
                    <div class="col-sm-6 col-md-6 result-box__name">@match.Key</div>
                    <div class="col-sm-6 col-md-6 result-box__half"></div>
                </div>
                @foreach (var item in match)
                {
                    <div class="col-sm-12 col-md-12 result-box__match row">
                        <div class="col-sm-4 col-md-4 result-box__item">@($"{item.Date:dd/MM/yyyy H:mm}")</div>
                        <div class="col-sm-6 col-md-6 result-box__item result-box__item_date">@item.MatchName</div>
                        <div class="col-sm-2 col-md-2 result-box__item result-box__item_score">@item.Team1Score - @item.Team2Score</div>
                    </div>
                }
            </div>
        }
        <div style="margin-top:20px;">
            Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
        </div>
        @Html.PagedListPager(Model, page => Url.Action("ShowResults", "Results", new { page, date1 = ViewBag.date1, date2 = ViewBag.date2, sport = ViewBag.sport }))

    </div>
</div>
<hr />

@Styles.Render("~/Content/ResultsForm.css")

@section scripts {
    <script type="text/javascript">

        //$(document).ready(function () {
        //    $.datepicker.setDefaults($.datepicker.regional["ru-Ru"]);
        //    $(function () {
        //        $("#date1").datepicker({
        //            showAnim: "slide",
        //            yearRange: "2016:2020"
        //        });
        //    });
        //    $(function () {
        //        $("#date2").datepicker({
        //            showAnim: "slide",
        //            yearRange: "2016:2020"
        //        });
        //    });

        //});
    </script>
}