RosBets/Controllers/BetController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RosBets.Context;
using RosBets.Models;
using RosBets.ViewModels;

namespace RosBets.Controllers
{
    public class BetController : Controller
    {
      //  RosBetsContext db = new RosBetsContext();

        [ChildActionOnly]
        public ActionResult RenderCoupon()
        {
            var coupon = Coupon.GetCoupon(HttpContext);
            var viewmodel = new CouponViewModel
            {
                CouponEvents = coupon.GetCouponEvents(),
                TotalCoefficient = coupon.GetCoefficient()
            };
            return PartialView("right_column", viewmodel);
        }

        [HttpPost]
        public ActionResult AddToCoupon(string id)
        {
            using (var db = new RosBetsContext())
            {
                var ids = id.Split('_');
                var eventId = int.Parse(ids[0]);
                var matchId = int.Parse(ids[1]);
                var matchEvent = db.MatchEvents.SingleOrDefault(m => m.EventId == eventId && m.MatchId == matchId);
                var coupon = Coupon.GetCoupon(HttpContext);
                if (matchEvent != null)
                {
                    coupon.AddToCoupon(matchEvent);
                }
                var viewmodel = new CouponViewModel
                {
                    CouponEvents = coupon.GetCouponEvents(),
                    TotalCoefficient = coupon.GetCoefficient()
                };

                return PartialView("right_column", viewmodel);
            }
        }

        [HttpPost]
        public ActionResult RemoveFromCoupon(int id)
        {
            var coupon = Coupon.GetCoupon(HttpContext);
            coupon.RemoveFromCoupon(id);
            var viewmodel = new CouponViewModel
            {
                CouponEvents = coupon.GetCouponEvents(),
                TotalCoefficient = coupon.GetCoefficient()
            };
            return PartialView("right_column", viewmodel);
        }

        [HttpPost]
        public ActionResult ClearCoupon()
        {
            var coupon = Coupon.GetCoupon(HttpContext);
            coupon.ClearCoupon();
            var viewmodel = new CouponViewModel
            {
                CouponEvents = coupon.GetCouponEvents(),
                TotalCoefficient = coupon.GetCoefficient()
            };
            return PartialView("right_column", viewmodel);
        }

        [HttpPost]
        public ActionResult CreateBet(decimal amount, int? couponEventId)
        {
            using (var db = new RosBetsContext())
            {
                if (!User.Identity.IsAuthenticated)
                {
                    return Json(new {result = "NotLoggedIn"});
                }
                var coupon = Coupon.GetCoupon(HttpContext);
                var user = db.Users.FirstOrDefault(x => x.Mail == User.Identity.Name);
                if (user.Money < amount)
                {
                    return Json(new {result = "NoMoney"});
                }
                var bet = new Bet
                {
                    UserId = user.Id,
                    BetAmount = amount,
                    Date = DateTime.Now
                };
                db.Bets.Add(bet);
                user.Money -= amount;
                db.SaveChanges();
                coupon.CreateBet(bet, couponEventId);
                var viewmodel = new CouponViewModel
                {
                    CouponEvents = coupon.GetCouponEvents(),
                    TotalCoefficient = coupon.GetCoefficient()
                };
                return PartialView("right_column", viewmodel);
            }
        }

        [HttpPost]
        public ActionResult AllOrdinary(params BetTO[] couponEvents)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Json(new { result = "NotLoggedIn" });
            }
            var user = new User();
            using (var db = new RosBetsContext())
            {
                user = db.Users.FirstOrDefault(x => x.Mail == User.Identity.Name);
            }
            var betAmount = couponEvents.Sum(x => x.Value);
            if (betAmount > user.Money)
            {
                return Json(new {result = "NoMoney"});
            }
            var coupon = Coupon.GetCoupon(HttpContext);
            foreach (var e in couponEvents)
            {
                var bet = new Bet
                {
                    UserId = user.Id,
                    BetAmount = e.Value,
                    Date = DateTime.Now
                };
                using (var db = new RosBetsContext())
                {
                    db.Bets.Add(bet);
                    user.Money -= e.Value;
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                    coupon.CreateBet(bet, e.EventId);
                }
            }
            var viewmodel = new CouponViewModel
            {
                CouponEvents = coupon.GetCouponEvents(),
                TotalCoefficient = coupon.GetCoefficient()
            };
            return PartialView("right_column", viewmodel);
            
        }
    }
}

RosBets/Views/Shared/_HistoryTable.cshtml
@model List<RosBets.Models.Bet>

@foreach (var bet in Model)
{
    var cl = (bet.Success == true && bet.Success != null) ? "success" : "defeat";
    if (bet.Success == null) { cl = "null"; }
    <div class="panel-group story-panel @cl">
        <div id="historyTable" class="panel panel-default">
            <div class="toggle-list-header panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#colapse_@bet.Id">
                        @if (bet.BetEvents.Count == 1)
                {<span>Ординар</span>}
                else
                {<span>Экспресс</span> }
                        <span>от @($"{bet.Date:dd/MM/yyyy H:mm}")</span>
                        <span>на сумму: @bet.BetAmount</span>
                        @* @if (bet.Success == null)
                            {<span class="null">Не расчитано</span>}
                            else if (bet.Success == true)
                            {<span class="success">Успех</span>}
                            else
                            {<span class="defeat">Провал</span>}
                                    <span>@bet.BetAmount р.</span>
                                    <span>Коэффицент: @bet.TotalCoefficient</span>
                        *@
                        @if (bet.Success == null)
                        {
                            <span> Возможный выигрыш: @bet.Payout р.</span>
                        }
                        @if (bet.Success != null)
                        {
                            <span> Выигрыш: @bet.Payout р.</span>
                        }

                    </a>
                </h4>
            </div>
            <div id="colapse_@bet.Id" class="panel-collapse collapse toggle-list">
                <div class="panel-body">
                    <table class="table" id="ourtable">
                        <thead>
                        <tr>
                            <th>Дата матча</th>
                            <th>Чемпионат</th>
                            <th>Матч</th>
                            <th>Событие</th>
                            <th>Результат</th>
                            <th>Успешность</th>
                            <th>Коэффицент</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach (var betEvent in bet.BetEvents)
                            {
                                <tr>
                                    <td>@($"{betEvent.Match.Date:dd/MM/yyyy H:mm}")</td>
                                    <td>@betEvent.Match.Championship.Name</td>
                                    <td>@betEvent.Match.MatchName</td>
                                    <td>@betEvent.Event.FullName @betEvent.Total</td>
                                    <td>@betEvent.Match.Team1Score - @betEvent.Match.Team2Score</td>
                                    <td>@betEvent.BetEventStatus.Status</td>
                                    <td>@betEvent.Coefficient</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

RosBets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/owl.carousel.css")
</head>
<body>
    <div id="back-layer">
        @{Html.RenderAction("RenderHeader", "Home");}
        <section id="section" class="index-page">
            <div class="row no-gutters">
                <div class="left-menu col-md-2 col-xs-12">
                    @{Html.RenderAction("RenderLineSelect", "Home");}
                </div>
            <div class="main background-main col-md-8 col-xs-12">
                @RenderBody()
            </div>
                <div class="cupon-menu col-md-2 col-xs-12">
                    @{Html.RenderAction("RenderCoupon", "Bet");}
                </div>
            </div>
        </section>
        @{Html.RenderPartial("footer");}
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/owl.carousel")
        @Scripts.Render("~/bundles/inputmask")
        @RenderSection("scripts", required: false)
    </div>
    <script>
    $(document).ready(function () {
        $(".owl-carousel").owlCarousel({
            loop: true,
            nav: true,
            items: 1,
            navText: ['<i class="fa fa-angle-left" aria-hidden="true"></i>', '<i class="fa fa-angle-right" aria-hidden="true"></i>'],            
            autoplay: 3000,
            autoplayHoverPause: false
        });
    });
    </script>
</body>
</html>

RosBets/Views/Shared/_MatchInfo.cshtml
@using System.Globalization
@model RosBets.Models.Match

<tr><td colspan="14" class="match-table-border"></td></tr>
<tr>
    <td class="td-colspan-up">@($"{Model.Date:dd/MM}")</td>
    <td class="td-colspan-up">@Model.Team1Name</td>

    <td rowspan="2" id="1_@Model.Id">@Model.MatchEvents.Where(x=>x.EventId == 1 && x.MatchId==Model.Id).Select(e=>e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>

    <td rowspan="2" class="table-td" id="2_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 2 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>
    <td rowspan="2" class="table-td" id="3_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 3 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>

    
    <td rowspan="2" class="table-td" id="4_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 4 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>
    <td rowspan="2" class="table-td" id="5_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 5 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>
    <td rowspan="2" class="table-td" id="6_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 6 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>
    
    <td rowspan="2" class="table-td" id="7_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 7 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>
    <td rowspan="2" class="table-td" id="8_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 8 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>
    <td rowspan="2" class="table-td" id="9_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 9 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>

    <td id="10_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 10 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>

    <td class="table-td" id="11_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 11 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>
    <td class="table-td" id="12_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 12 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>

</tr>
<tr>
    <td>@($"{Model.Date:H:mm}")</td>
    <td>@Model.Team2Name</td>

    <td id="13_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 13 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>

    <td class="table-td" id="14_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 14 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>
    <td class="table-td" id="15_@Model.Id">@Model.MatchEvents.Where(x => x.EventId == 15 && x.MatchId == Model.Id).Select(e => e.EventValue).SingleOrDefault().ToString(CultureInfo.InvariantCulture)</td>

</tr>

RosBets/Views/Shared/header.cshtml
@model string


<!--header-->
<header id="header" class="header navbar-fixed-top">
    <div class="row">
        <!--navbar-->
        <div class="navbar navbar-inverse col-sm-12 col-md-6">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("RosBets", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("АПЛ", "Index", "Line",new { id = 6 },null)</li>
                    <li>@Html.ActionLink("Бундеслига", "Index", "Line",new { id=5 },null)</li>
                    <li>@Html.ActionLink("НХЛ", "Index", "Line", new { id = 11 }, null)</li>
                    <li>@Html.ActionLink("Результаты", "ShowResults", "Results")</li>
                </ul>
            </div>
        </div>
        <!--/navbar-->
        <!--userbar-->
        <div class="user-bar col-sm-12 col-md-6">
            <div class="container">
                <div class="row">
                    
                    @if (!User.Identity.IsAuthenticated)
                    {                       
                        
                        <div class="bar login col-xs-12 col-sm-6 col-md-6">
                            <div class="round-box">
                                <a class="circle" href="/Account/Registration">
                                    <i class="fa fa-sign-in fa-1x"></i>
                                </a>
                                <span class="text" href="#">Регистрация</span>
                            </div>
                            
                        </div>

                        <div class="bar login col-xs-12 col-sm-6 col-md-6">
                            <div class="round-box">
                                <a class="circle" href="/Account/Login">
                                    <i class="fa fa-sign-in fa-1x"></i>
                                </a>
                                <span class="text" href="#">Вход</span>
                            </div>
                        </div>
                    }
                    else
                    {                        
                        <div class="bar user col-xs-12 col-sm-4 col-md-4">
                            <div class="round-box">
                                <a class="circle" href="/Account/Details">
                                    <i class="fa fa-user fa-1x"></i>
                                </a>
                                <span class="text" href="#">@User.Identity.Name</span>
                            </div>
                        </div>
                        <div class="bar money col-xs-12 col-sm-4 col-md-4">
                            <div class="round-box">
                                <a class="circle" href="/Money/">
                                    <i class="fa fa-money fa-1x"></i>
                                </a>
                                <span class="text" href="#">@Model р.</span>
                            </div>
                        </div>
                        <div class="bar login col-xs-12 col-sm-4 col-md-4">
                            <div class="round-box">
                                <a class="circle" href="javascript:document.getElementById('logoutForm').submit()">
                                    <i class="fa fa-sign-out fa-1x"></i>
                                </a>
                                <span class="text" href="#">Выход</span>
                            </div>
                            @using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                            }
                        </div>
                    }

                </div>
            </div>
        </div>
        <!--/userbar-->
    </div>
    <div class="line"></div>
</header>
<!--/header-->

RosBets/Views/Shared/left_column.cshtml
@model List<RosBets.Models.Sport>

    <h2 class="left-menu-header">Линия</h2>
    <!--Championship toggle list start-->
    <div class="sports panel-group toggle-block">
        <div class="panel panel-default">
            @foreach (var sport in Model)
            {
                <div class="toggle-list-header panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#@sport.Id">@sport.Name</a><!--kind of sport-->
                    </h4>
                </div>
                <div id="@sport.Id" class="panel-collapse collapse toggle-list">
                    <ul class="list-group">
                        <!--Championship list-->
                        @foreach (var championship in sport.Championships)
                        {
                            <li><a href="/Line/@championship.Id">@championship.Name</a></li>
                        }
                    </ul>
                </div>
            }
            <div class="toggle-list-header panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#Filter">Ставки</a>
                </h4>
            </div>
            <div id="Filter" class="panel-collapse collapse toggle-list">
                <ul class="list-group">

                    <li><a href="/FilterLine/Index?id=1">Не важно когда</a></li>
                    <li><a href="/FilterLine/Index?id=2">Сегодня</a></li>
                    <li><a href="/FilterLine/Index?id=3">Ближайший час</a></li>
                </ul>
            </div>
            </div>
    </div>
    <!--Championship toggle list end-->

RosBets/Views/Shared/right_column.cshtml
@model RosBets.ViewModels.CouponViewModel

<div class="right-menu-header">
    <i class="fa fa-times fa-bigcross"></i>
    <h2>Купон</h2>
</div>
<div class="login-error coupon-message">
    Создание ставок доступно только зарегистрированным пользователям.
</div>
<div class="money-error coupon-message">
    Недостаточно денег для создания ставки.
</div>
<div class="bet-success coupon-message">
    Ставка создана.
</div>
@if (Model.CouponEvents.Count > 0)
{
    if (Model.CouponEvents.Count > 1)
    { 
        <div class="coupon-tabs">
            <ul class="nav nav-tabs toggle-coupon text-center">
                <li class="active">
                    <a data-toggle="tab" href="#ordinar">Ординар</a>
                </li>
                <li>
                    <a data-toggle="tab" href="#express">Экспресс</a>
                </li>
            </ul>
        </div>
    }
    <div class="tab-content">
        @if (Model.CouponEvents.Count > 1)
        {
        <div id="express" class="tab-pane fade">
            @foreach (var couponEvent in Model.CouponEvents)
            {
                <div class="col coupon clearfix">
                    <i class="fa fa-times fa-coupon" aria-hidden="true" data-bind-id="@($"{couponEvent.EventId}_{couponEvent.MatchId}")" id="@couponEvent.Id"></i>
                    <span class="match-name coupon-span">@couponEvent.Match.MatchName</span>
                    <span class="coupon-date coupon-span">@($"{couponEvent.Match.Date:dd.MM hh.mm}")</span>
                    <span class="event-name coupon-span">@couponEvent.Event.FullName @couponEvent.Total</span>
                    <div class="coefficient-name coupon-span float-elem-left">Коэффицент</div>
                    <div class="coefficient coupon-span float-elem-right">@couponEvent.Coefficient</div>
                </div>
            }

            <div class="col coupon coupon-summary coupon clearfix">
                <span class="coupon-span float-elem-left">Общий коэффицент:</span>
                <span class="coefficient coupon-span float-elem-right" id="exp-total-coeff">@Model.TotalCoefficient</span>
                <div class="express-summary">
                    <span class="coupon-span float-elem-left">Возможный результат:</span>
                    <span class="coefficient coupon-span float-elem-right" id="express-sum"></span>
                </div>
                <input id="expressBetValue" class="float-elem-left coupon-input" name="amount"/>
                <div class="submitExpress float-elem-right coupon-button">Поставить</div>
            </div>
        </div>
        }

        <div id="ordinar" class="tab-pane fade in active clearfix">
            @foreach (var couponEvent in Model.CouponEvents)
            {
                <div class="col coupon clearfix">
                    <i class="fa fa-times fa-coupon" aria-hidden="true" data-bind-id="@($"{couponEvent.EventId}_{couponEvent.MatchId}")" id="@couponEvent.Id"></i>
                    <span class="match-name coupon-span">@couponEvent.Match.MatchName</span>
                    <span class="coupon-date coupon-span">@($"{couponEvent.Match.Date:dd.MM hh.mm}")</span>
                    <span class="event-name coupon-span">@couponEvent.Event.FullName @couponEvent.Total</span>
                    <div class="coefficient-name coupon-span float-elem-left">Коэффицент</div>
                    <div class="coefficient coupon-span float-elem-right">@couponEvent.Coefficient</div>
                    <input id="value_@couponEvent.Id" class="float-elem-left coupon-input ord-input" name="amount">
                    <div data-id="@couponEvent.Id" class="submitOrdinary float-elem-right coupon-button-small">>></div>                  
                </div>
                <div class="empty-input coupon-message" data-msgid="@couponEvent.Id">Введите сумму ставки.</div>

            }

            <div class="col coupon coupon-summary coupon clearfix">
                <span class="coupon-span float-elem-left">Общий коэффицент:</span>
                <span class="coefficient coupon-span float-elem-right" id="ord-total-coeff">@Model.TotalCoefficient</span>
                <div class="ordinary-summary">
                    <span class="coupon-span float-elem-left">Общая сумма ставки:</span>
                    <span class="coefficient coupon-span float-elem-right" id="ordinary-sum"></span>
                    <span class="coupon-span float-elem-left">Возможный результат:</span>
                    <span class="coefficient coupon-span float-elem-right" id="ordinary-payout"></span>
                </div>
                <input id="allOrdinary" class="float-elem-left coupon-input" />
                <div class="allOrdinary float-elem-right coupon-button">Поставить</div>
            </div>
        </div>

    </div>
    
}